import {ListStep} from "./getDataStep";
export class ListDetail {
  constructor(public ap_no?: any,
              public sub_id?: any,
              public fin_typ?: any,
              public sub_fin?: any,
              public buy_back_flg?: any,
              public adv_arr?: any,
              public schedule?: any,
              public asst_amt_e_vat?: any,
              public asst_amt_vat?: any,
              public asst_amt_i_vat?: any,
              public fin_amt_e_vat?: any,
              public fin_amt_vat?: any,
              public fin_amt_i_vat?: any,
              public fin_ratio?: any,
              public down_amt_e_vat?: any,
              public down_amt_vat?: any,
              public down_amt_i_vat?: any,
              public dep_amt_e_vat?: any,
              public dep_amt_vat?: any,
              public dep_amt_i_vat?: any,
              public rv_amt_e_vat?: any,
              public rv_amt_vat?: any,
              public rv_amt_i_vat?: any,
              public cal_inst_typ?: any,
              public installment_e_vat?: any,
              public installment_vat?: any,
              public installment_i_vat?: any,
              public bank_code?: any,
              public interest_rate_type?: any,
              public interest_rate?: any,
              public terms?: any,
              public flat_rate?: any,
              public gross_irr?: any,
              public net_irr?: any,
              public spread?: any,
              public currency?: any,
              public disburse_dt?,
              public first?: any,
              public operating_lease?: any,
              public wh_tax?: any,
              public lc_flg?: any,
              public fin_asst?: any,
              public es_expense?: any,
              public es_revenue?: any,
              public net_irr_inc_deposit?: any,
              public asst_prce_forgn?: any,
              public group_flg?: any,
              public group_nme?: any,
              public with_vat?: any,
              public wh_tax_flg?: any,
              public curr_type?: any,
              public duty_pcnt?: any,
              public inst_pcnt_of_asst?: any,
              public type_cal_pricing?: any,
              public fin_type_name?: any,
              public sub_fin_name?: any,
              public operating_lease_name?: any,
              public curr_type_name?: any,
              public int_rate_name?: any,
              public adv_arr_name?: any,
              public inputIvat?: any,
              public listStep?: ListStep[]) {
  }

  static parse(jsons: any[]) {
    let data: ListDetail[] = [];
    for (let json of jsons) {
      data.push(new ListDetail(
        json.AP_NO,
        json.SUB_ID,
        json.FIN_TYP,
        json.SUB_FIN,
        json.BUY_BACK_FLG,
        json.ADV_ARR,
        json.SCHEDULE,
        json.ASST_AMT_E_VAT,
        json.ASST_AMT_VAT,
        json.ASST_AMT_I_VAT,
        json.FIN_AMT_E_VAT,
        json.FIN_AMT_VAT,
        json.FIN_AMT_I_VAT,
        json.FIN_RATIO,
        json.DOWN_AMT_E_VAT,
        json.DOWN_AMT_VAT,
        json.DOWN_AMT_I_VAT,
        json.DEP_AMT_E_VAT,
        json.DEP_AMT_VAT,
        json.DEP_AMT_I_VAT,
        json.RV_AMT_E_VAT,
        json.RV_AMT_VAT,
        json.RV_AMT_I_VAT,
        json.CAL_INST_TYP,
        json.INSTALLMENT_E_VAT,
        json.INSTALLMENT_VAT,
        json.INSTALLMENT_I_VAT,
        json.BANK_CODE,
        json.INTEREST_RATE_TYPE,
        json.INTEREST_RATE,
        json.TERMS,
        json.FLAT_RATE,
        json.GROSS_IRR,
        json.NET_IRR,
        json.SPREAD,
        json.CURRENCY,
        json.DISBURSE_DT,
        json.FIRST,
        json.OPERATING_LEASE,
        json.WH_TAX,
        json.LC_FLG,
        json.FIN_ASST,
        json.ES_EXPENSE,
        json.ES_REVENUE,
        json.NET_IRR_INC_DEPOSIT,
        json.ASST_PRCE_FORGN,
        json.GROUP_FLG,
        json.GROUP_NME,
        json.WITH_VAT,
        json.WH_TAX_FLG,
        json.CURR_TYPE,
        json.DUTY_PCNT,
        json.INST_PCNT_OF_ASST,
        json.TYPE_CAL_PRICING,
        json.FIN_TYPE_NAME,
        json.SUB_FIN_NAME,
        json.OPERATING_LEASE_NAME,
        json.CURR_TYPE_NAME,
        json.INT_RATE_NAME,
        json.ADV_ARR_NAME,
        json.inputIVat,
        ListStep.parse(json.STEP)
      ))
    }
    return data;
  }
}
